import {
  ArrowDownLeft,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  BookMarked,
  BookOpen,
  Boxes,
  CalendarRange,
  FileText,
  HandCoins,
  Landmark,
  LayoutDashboard,
  Package,
  PackageMinus,
  PackagePlus,
  PieChart,
  PlayCircle,
  Receipt,
  Scale,
  ScanLine,
  Settings,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  Upload,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { NavIcon as NavIconName } from "@/lib/constants";

/**
 * Icon names are strings in the navigation config so the config stays a plain
 * data file, importable anywhere without dragging the icon library along. The
 * mapping to real components happens here, once.
 */
const ICONS: Record<NavIconName, LucideIcon> = {
  LayoutDashboard,
  ScanLine,
  BadgeCheck,
  Receipt,
  ShoppingCart,
  Boxes,
  UserCheck,
  Truck,
  BookOpen,
  Wallet,
  Landmark,
  BarChart3,
  BookMarked,
  Scale,
  PlayCircle,
  CalendarRange,
  ShieldCheck,
  Settings,
  UserCog,
  Users,
  ArrowDownLeft,
  ArrowUpRight,
  Zap,
  FileText,
  Undo2,
  Package,
  PackagePlus,
  PackageMinus,
  SlidersHorizontal,
  TriangleAlert,
  UserPlus,
  Upload,
  HandCoins,
  PieChart,
  TrendingUp,
  Trash2,
  Warehouse,
};

export function NavIcon({ name, className }: { name: NavIconName; className?: string }) {
  const Icon = ICONS[name] ?? LayoutDashboard;
  return <Icon className={className} aria-hidden />;
}
